repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.48.0
  hooks:
#    - id: terraform_validate
    - id: terraform_fmt
    - id: terraform_docs_replace
      args: ['table']
      exclude: common/*.tf
      exclude: version.tf
      exclude: examples
#    - id: terraform_tflint 
#      args:  [ "--args=--config=__GIT_WORKING_DIR__/.tflint.hcl"]
#      exclude: examples
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
    - id: check-symlinks
    - id: detect-aws-credentials
    - id: detect-private-key
